
export const metadata = {
  title: "Articles Pages",
  description: "Generated by create next app",
};

export default function ({ children }) {
  return (
    <div className="flex gap-2 flex-col">
      <h1 className="font-bold text-3xl p-2">Articles</h1>
      <div>
        {children}
      </div>
    </div>
  )
}